/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Sala de jantar.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Sala(props) {
  const { nodes, materials } = useGLTF('/Sala de jantar.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.021, 0.415, 1.005]} rotation={[3.032, 0.813, -2.901]} scale={[0.176, 0.149, 0.181]}>
        <mesh geometry={nodes.Circle017.geometry} material={materials['Madeira.001']} />
        <mesh geometry={nodes.Circle017_1.geometry} material={materials.Estofado} />
      </group>
      <mesh geometry={nodes.Desc.geometry} material={materials.Madeira} position={[-1.365, 0.717, 0.044]} rotation={[0, Math.PI / 2, 0]} scale={[0.481, 0.648, 0.624]} />
      <mesh geometry={nodes.Jarro2.geometry} material={materials.MatJarro} position={[0.166, 0.766, 0.139]} scale={0.027} />
      <mesh geometry={nodes.JarroMaior.geometry} material={materials['Louça.001']} position={[-1.373, 0.697, 0.636]} rotation={[Math.PI, -0.665, Math.PI]} scale={0.083} />
      <mesh geometry={nodes.JarroMenos.geometry} material={materials.Louça} position={[-1.369, 0.696, 0.385]} scale={0.088} />
      <mesh geometry={nodes.mesajantar.geometry} material={materials['Madeira.002']} position={[0.165, 0.729, 0.067]} scale={[0.463, 1, 0.932]} />
      <group position={[0.796, 0.28, 0.628]} rotation={[3.039, -0.752, -3.051]} scale={[0.176, 0.149, 0.181]}>
        <mesh geometry={nodes.Circle001.geometry} material={materials['Madeira.001']} />
        <mesh geometry={nodes.Circle001_1.geometry} material={materials.Estofado} />
      </group>
      <group position={[0.796, 0.28, 0.067]} rotation={[3.039, -0.752, -3.051]} scale={[0.176, 0.149, 0.181]}>
        <mesh geometry={nodes.Circle002.geometry} material={materials['Madeira.001']} />
        <mesh geometry={nodes.Circle002_1.geometry} material={materials.Estofado} />
      </group>
      <group position={[0.796, 0.28, -0.476]} rotation={[3.039, -0.752, -3.051]} scale={[0.176, 0.149, 0.181]}>
        <mesh geometry={nodes.Circle003.geometry} material={materials['Madeira.001']} />
        <mesh geometry={nodes.Circle003_1.geometry} material={materials.Estofado} />
      </group>
      <group position={[-0.45, 0.28, -0.494]} rotation={[0.103, 0.752, 0.091]} scale={[0.176, 0.149, 0.181]}>
        <mesh geometry={nodes.Circle008.geometry} material={materials['Madeira.001']} />
        <mesh geometry={nodes.Circle008_1.geometry} material={materials.Estofado} />
      </group>
      <group position={[-0.45, 0.28, 0.067]} rotation={[0.103, 0.752, 0.091]} scale={[0.176, 0.149, 0.181]}>
        <mesh geometry={nodes.Circle009.geometry} material={materials['Madeira.001']} />
        <mesh geometry={nodes.Circle009_1.geometry} material={materials.Estofado} />
      </group>
      <group position={[-0.45, 0.28, 0.61]} rotation={[0.103, 0.752, 0.091]} scale={[0.176, 0.149, 0.181]}>
        <mesh geometry={nodes.Circle010.geometry} material={materials['Madeira.001']} />
        <mesh geometry={nodes.Circle010_1.geometry} material={materials.Estofado} />
      </group>
      <group position={[0.161, 0.28, -0.997]} rotation={[0.109, -0.813, 0.241]} scale={[0.176, 0.149, 0.181]}>
        <mesh geometry={nodes.Circle012.geometry} material={materials['Madeira.001']} />
        <mesh geometry={nodes.Circle012_1.geometry} material={materials.Estofado} />
      </group>
      <group position={[0.141, 0.971, 0.133]} rotation={[-Math.PI, 0.072, -Math.PI]} scale={0.012}>
        <mesh geometry={nodes.Circle079.geometry} material={materials.Caule} />
        <mesh geometry={nodes.Circle079_1.geometry} material={materials.Flores} />
      </group>
    </group>
  )
}

useGLTF.preload('/Sala de jantar.glb')
